### ISSUE TITLE
建立虛擬機出現錯誤

### ISSUE THREAD

**Issue by ghost7476** [superj80820/cloud-gaming#1]
![image](https://user-images.githubusercontent.com/49386802/65003179-eaf01580-d929-11e9-9717-77c888592ffc.png)
這些指令打完之後出現Error,然後看虛擬機器頁面沒有VM被建立,不知道是出現甚麼問題

RunningWARNING: Some requests generated warnings:
 - Disk size: '150 GB' is larger than image size: '50 GB'. You might need to resize the root repartition manually if the operating system does not support automatic resizing. See https://cloud.google.com/compute/docs/disks/add-persistent-disk#r
esize_pd for details.
 - The resource 'projects/windows-cloud/global/images/windows-server-2016-dc-v20190709' is deprecated. A suggested replacement is 'projects/windows-cloud/global/images/windows-server-2016-dc-v20190725'.
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Quota 'SSD_TOTAL_GB' exceeded.  Limit: 100.0 in region asia-east1.

**Comment by superj80820** [comment]
感謝你的回報~

1. GPUS_ALL_REGIONS: 為"GPU沒有申請" 文章裡面有教學
https://github.com/superj80820/cloud-gaming/blob/master/tutorial/applyGPU.md
2. SSD_TOTAL_GB: 為你的SSD最大容量只能100GB 這滿妙的 因為我沒申請就高於這個容量 你可以按照GPU申請的方式再申請容量 另外我晚點改Code讓SSD硬碟容量為可調

**Comment by ghost7476** [comment]
![image](https://user-images.githubusercontent.com/49386802/65015677-c5c4cc80-d954-11e9-84f4-c791368169f4.png)
![image](https://user-images.githubusercontent.com/49386802/65015712-db39f680-d954-11e9-935f-6dc8cecbfda8.png)
![image](https://user-images.githubusercontent.com/49386802/65015740-ed1b9980-d954-11e9-9c6d-cf8371b0b036.png)

看了一下腳本
--boot-disk-size=150GB \
--boot-disk-type=pd-ssd \
所以我要申請Persistent Disk SSD (GB)是吧？

**Comment by superj80820** [comment]
是的 你可以用以下方法申請更多的SSD大小
![](https://i.imgur.com/KZWATVP.png)
或者 你也可以先fork一份到你的github 然後更改腳本

**Comment by superj80820** [comment]
https://github.com/superj80820/cloud-gaming/commit/3249e48a45704fc91581cdeade77e80abdf53967

我以新增輸入disk大小功能(至少要高於80GB)🧔

**Comment by superj80820** [comment]
如果沒問題了請回報給我 感謝～

**Comment by ghost7476** [comment]
![image](https://user-images.githubusercontent.com/49386802/65054453-26c5c200-d9a0-11e9-85e9-0e8195c407cc.png)

看起來是 preemption的時候出了問題。

**Comment by ghost7476** [comment]
![image](https://user-images.githubusercontent.com/49386802/65054736-9f2c8300-d9a0-11e9-8147-99053f37f9e5.png)

看起來容量是有增加了

**Comment by ghost7476** [comment]
![image](https://user-images.githubusercontent.com/49386802/65055706-4231cc80-d9a2-11e9-8422-7ad6a79b430e.png)

preemption選No就沒有問題。

**Comment by superj80820** [comment]
1. preemption出現問題: Log看不太出來到底是發生了什麼事 只知道出現問題Xdd 
你可以手動選創建VM試看看嗎 勾選的配置如圖
(另外提醒 如果可以的話你可以選擇台灣不同的p100 GPU 盡量使用preemption模式 這樣比較便宜 以你的虛擬機來說約每小時便宜0.8鎂)
![New Project (1)](https://user-images.githubusercontent.com/35736479/65111228-c1101f00-da0d-11e9-92c5-19847bf1cdfc.png)
2. Dcard問題 花費怎麼算的: 我以新增[這張Issue](https://github.com/superj80820/cloud-gaming/issues/3)用來告知使用者創建的虛擬機每小時將會花費多少元
